name: pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        npm init -y
        npm install @slidev/cli slidev-theme-dracula

    - name: build
      run: |
        npx slidev build
